// <auto-generated />
using System;
using CP.Portal.Movies.Module.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CP.Portal.Movies.Module.Data.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20251120150239_InitialMovies")]
    partial class InitialMovies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("movies")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.Genre", b =>
                {
                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("genre_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("GenreId")
                        .HasName("pk_genre");

                    b.ToTable("genre", "movies");

                    b.HasData(
                        new
                        {
                            GenreId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Action"
                        },
                        new
                        {
                            GenreId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Drama"
                        },
                        new
                        {
                            GenreId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Comedy"
                        },
                        new
                        {
                            GenreId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            GenreId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Thriller"
                        },
                        new
                        {
                            GenreId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Fantasy"
                        },
                        new
                        {
                            GenreId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.Movie", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("original_title");

                    b.Property<DateOnly>("ReleaseYear")
                        .HasColumnType("date")
                        .HasColumnName("release_year");

                    b.Property<decimal>("RentalPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("rental_price");

                    b.Property<string>("Synopsis")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("synopsis");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("MovieId")
                        .HasName("pk_movies");

                    b.ToTable("movies", "movies");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.MovieCast", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("CharacterName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("character_name");

                    b.Property<int>("CastOrder")
                        .HasColumnType("integer")
                        .HasColumnName("cast_order");

                    b.HasKey("MovieId", "PersonId", "CharacterName")
                        .HasName("pk_movies_cast");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_movies_cast_person_id");

                    b.HasIndex("MovieId", "CastOrder")
                        .HasDatabaseName("ix_movies_cast_movie_id_cast_order");

                    b.ToTable("movies_cast", "movies");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.MovieCrew", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role");

                    b.HasKey("MovieId", "PersonId", "Role")
                        .HasName("pk_movies_crew");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_movies_crew_person_id");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_movies_crew_role");

                    b.ToTable("movies_crew", "movies");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.MovieGenre", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("genre_id");

                    b.HasKey("MovieId", "GenreId")
                        .HasName("pk_movies_genres");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_movies_genres_genre_id");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_movies_genres_movie_id");

                    b.ToTable("movies_genres", "movies");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Bio")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.HasKey("PersonId")
                        .HasName("pk_person");

                    b.ToTable("person", "movies");

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Bio = "Director.",
                            BirthDate = new DateTime(1970, 7, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Christopher Nolan"
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Bio = "Actor.",
                            BirthDate = new DateTime(1964, 9, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Keanu Reeves"
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Bio = "Actress.",
                            BirthDate = new DateTime(1967, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Carrie-Anne Moss"
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Bio = "Actor.",
                            BirthDate = new DateTime(1974, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Leonardo DiCaprio"
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Bio = "Composer.",
                            BirthDate = new DateTime(1957, 9, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Hans Zimmer"
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Bio = "Director.",
                            BirthDate = new DateTime(1963, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Quentin Tarantino"
                        },
                        new
                        {
                            PersonId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Bio = "Director.",
                            BirthDate = new DateTime(1954, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "James Cameron"
                        });
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.MovieCast", b =>
                {
                    b.HasOne("CP.Portal.Movies.Module.Data.Movie", "Movie")
                        .WithMany("Cast")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movies_cast_movies_movie_id");

                    b.HasOne("CP.Portal.Movies.Module.Data.Person", "Person")
                        .WithMany("CastCredits")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movies_cast_people_person_id");

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.MovieCrew", b =>
                {
                    b.HasOne("CP.Portal.Movies.Module.Data.Movie", "Movie")
                        .WithMany("Crew")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movies_crew_movies_movie_id");

                    b.HasOne("CP.Portal.Movies.Module.Data.Person", "Person")
                        .WithMany("CrewCredits")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movies_crew_people_person_id");

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.MovieGenre", b =>
                {
                    b.HasOne("CP.Portal.Movies.Module.Data.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movies_genres_genre_genre_id");

                    b.HasOne("CP.Portal.Movies.Module.Data.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movies_genres_movies_movie_id");

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.Movie", b =>
                {
                    b.Navigation("Cast");

                    b.Navigation("Crew");

                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.Person", b =>
                {
                    b.Navigation("CastCredits");

                    b.Navigation("CrewCredits");
                });
#pragma warning restore 612, 618
        }
    }
}
